### ISSUE TITLE
Undefined result

### ISSUE THREAD

**Issue by iamriz7** [EvanZhouDev/bard-ai#1]
![image](https://github.com/EvanZhouDev/bard-ai/assets/66578450/e5f439a5-239b-4e59-b0be-895b23958d7f)

**Comment by EvanZhouDev** [comment]
There are two things that could have happened:
(because it works for me when I install my package locally and write the exact same code)
1. You have used Bard too much, and it has temporarily suspended you from the platform (which can happen). If this is so, wait 12-24 hours, and your access should be restored. You can verify that you indeed got suspended if you go to bard.google.com and can't ask Bard there either.
2. You may not be on the latest version of `bard-ai`, which is currently 1.0.6. Try running `npm update` or the equivalent on your project.

Let me know if these things don't help, and I will look into it further!

**Comment by EvanZhouDev** [comment]
Any update on this? If not, then closing issue.
