### ISSUE TITLE
undefined even though i use another psid its still undefined.. 

### ISSUE THREAD

**Issue by jonvicbarcenas** [EvanZhouDev/bard-ai#10]
![image](https://github.com/EvanZhouDev/bard-ai/assets/48144626/c0a03d6a-b7f0-4806-b7fe-9df35c5ff16f)

**Comment by EvanZhouDev** [comment]
Hmm... Your code seems to be correct. Make sure your API key is correct, and that it's exactly `__Secure-1PSID`. You should only have one such key, so I don't know where you would get another (unless through multiple accounts). Otherwise, check network and make sure you can use Bard normally. You may also get undefined if you surpass your daily "usage limit," which exists to some degree.

Without any more information, I cannot necessarily help.

**Comment by EvanZhouDev** [comment]
Has it been resolved? Closing otherwise...

**Comment by EvanZhouDev** [comment]
Closing.

**Comment by kim-dev-git** [comment]
It's happen because bard rate limiting, 200 request/hour.

after reaching the limit, all your request get throttled.
