### ISSUE TITLE
Replace axios with alova or Redaxios

### ISSUE THREAD

**Issue by ansarizafar** [EvanZhouDev/bard-ai#3]
axios is big ib size, please consider replacing it with alova https://github.com/alovajs/alova or Redaxios https://github.com/developit/redaxios

Please also add streaming reply support.

**Comment by EvanZhouDev** [comment]
Hi [ansarizafar](https://github.com/ansarizafar)!  I tried out Redaxios a while ago, but it doesn't seem to be the drop-in replacement it claims to be! And due to a lack of official docs for Redaxios specifically (as it works on Axios but not Redaxios), I can't seem to get it to work. I'll keep trying for a while and maybe even try out Alova (which seems to be larger?), but if you can help me out here, it would be amazing!

As for streaming, I'll be working on that very soon!

**Comment by EvanZhouDev** [comment]
2 quick updates:
1. I have replaced Axios with the native node fetch API, in v17.5 (which means it is now included in LTS). This means `bard-ai` is now dependency-less. I will be releasing the update soon.
2. Bard itself actually doesn't support streaming! `googlebard` "simulates" streaming by splitting up the words and just giving it to you word by word slowly. Its not actually a real stream! For that reason, I will not be implementing such a mechanism. View [this code](https://github.com/PawanOsman/GoogleBard/blob/cf6058e424ff6666065463fe73bbb9d84614a867/src/classes/bard.ts#L192).

**Comment by EvanZhouDev** [comment]
The update is now available in `v1.2.0`. If you have any further inquiries, let me know. Otherwise, I'll be closing this issue in a while.

**Comment by ansarizafar** [comment]
Thanks for the update.
