### ISSUE TITLE
Unsupported endgine

### ISSUE THREAD

**Issue by frankwo1** [EvanZhouDev/bard-ai#6]
Hi, I am getting an error message on NPM Install
EBADENGINE Unsupported engine {
npm WARN EBADENGINE   required: { node: '> 8.15.0', npm: '= 3.9.6' },
npm WARN EBADENGINE   current: { node: 'v14.20.0', npm: '9.5.0' }
npm WARN EBADENGINE }
Thanks
Frank

**Comment by EvanZhouDev** [comment]
Try updating the dependencies. This doesn't seem to be a `bard-ai` problem. It might be a problem with another dependency because I never set anything to require npm 3.9.6 only. Let me know if you find anything else, and try creating a clean project with only `bard-ai` and see if it still has the problem.

Hope this helps!

**Comment by frankwo1** [comment]
Thanks Evan, seems to have a conflict with node-fetch --- I will try a clean install without extra packages - might take me a bit of time since I am working with OpenAI now
Frank

**Comment by EvanZhouDev** [comment]
Okay! Glad you could figure it out.
