### ISSUE TITLE
✨ [FEATURE]: Integration With Gemini

### ISSUE THREAD

**Issue by Zoheb-Malik** [EvanZhouDev/bard-ai#68]
### Prerequisites

- [X] I have searched the [issues](https://github.com/EvanZhouDev/bard-ai/issues) and believe that it has not already been requested (and possibly rejected)
- [X] I am using the latest version of `bard-ai`

### Feature description

As people may be aware now, Gemini has been released! I came back to this repo and I see that it isn't being actively maintained, and I thought I'd voice my feelings about it... This project is too good to let go! Hopefully this request will spark a fire and get the ball rolling again 🙂 https://deepmind.google/technologies/gemini

**Comment by ThatXliner** [comment]
But it's not released yet, right?

**Comment by Zoheb-Malik** [comment]
> But it's not released yet, right?

It is @ThatXliner, Gemini Pro is apparently being utilised within Bard right now - although I'm unable to view it as I'm from the U.K.

Here's a list of all the countries where Gemini has been released: https://support.google.com/bard/answer/14294096

**Comment by ThatXliner** [comment]
From what I see, there theoretically shouldn't be any changes that need to be made to this library as Google is just updating Bard to use Gemini internally. I don't see any option to configure the web UI to *not* use Gemini.

Additionally, @EvanZhouDev [wants to encourage people](https://github.com/EvanZhouDev/bard-ai/issues/61#issuecomment-1754154332) to start using his [palm-api](https://github.com/EvanZhouDev/palm-api) library as this bard-ai library is buggy due to limits Google is placing on the web UIx

**Comment by matsyui** [comment]
holy molly
